import { chromium } from '/home/rogerkorantenng/dev/Hackathons/agentic-cinema/callsheet/node_modules/playwright-core/index.mjs';
import { writeFileSync } from 'node:fs';
const APP = 'http://localhost:5199/';
const res = [];
const ok = (name, pass, note = '') => { res.push([name, pass, note]); console.log(pass ? 'PASS' : 'FAIL', name, note); };
const b = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addInitScript(() => { if (!localStorage.getItem('dd-session')) localStorage.setItem('dd-session', 'click' + Date.now()); });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => { errs.push('native dialog ' + d.message()); d.dismiss(); });
const t = async (name, fn) => { try { const r = await fn(); ok(name, r !== false, typeof r === 'string' ? r : ''); } catch (e) { ok(name, false, e.message.split('\n')[0]); } };
await p.goto(APP); await p.waitForSelector('.attn');
await p.click('text=Reset demo'); await p.waitForTimeout(800);
for (const [n, h] of [['All disputes', 'All disputes'], ['The evidence', 'The evidence'], ['Surrender vs defend', 'Surrender vs defend'], ['Home', 'on the clock']])
  await t(`Sidebar: ${n}`, async () => { await p.click(`nav >> text=${n}`); await p.waitForTimeout(500); return (await p.locator('h1').first().innerText()).includes(h); });
await t('Compare: dispute select changes preview', async () => { await p.click('nav >> text=Surrender vs defend'); const o = await p.locator('#cmp option').nth(1).getAttribute('value'); await p.selectOption('#cmp', o); await p.waitForTimeout(700); return (await p.locator('.col.surrender').innerText()).includes('accept_dispute_claim'); });
await t('Compare: Open the full package', async () => { await p.click('text=Open this dispute'); await p.waitForSelector('.drawer'); await p.keyboard.press('Escape'); await p.waitForTimeout(300); return !(await p.locator('.drawer').count()); });
await p.click('nav >> text=Home');
await t('Theme toggle switches and persists', async () => { const before = await p.evaluate(() => document.documentElement.dataset.theme); await p.click('text=/(Light|Dark) theme/'); const after = await p.evaluate(() => document.documentElement.dataset.theme); await p.reload(); await p.waitForSelector('.attn'); return after !== before && (await p.evaluate(() => document.documentElement.dataset.theme)) === after; });
await t('Template radio selects second option', async () => { await p.locator('.seg', { hasText: 'Unauthorised charge' }).click(); return (await p.locator('.seg.on').innerText()).includes('Unauthorised'); });
await t('Deliver webhook creates a dispute and shows the result card', async () => { const n = await p.locator('tbody tr').count(); await p.click('.demo >> text=Deliver webhook'); await p.waitForSelector('.flow-res, .flow-head', { timeout: 30000 }); await p.waitForSelector('.flow-res', { timeout: 60000 }); return (await p.locator('tbody tr').count()) === n + 1; });
await t('Flow card: Open dispute button opens drawer', async () => { await p.click('.flow-res >> text=Open dispute'); await p.waitForSelector('.drawer'); return true; });
await t('Drawer: Escape closes', async () => { await p.keyboard.press('Escape'); await p.waitForTimeout(300); return !(await p.locator('.drawer').count()); });
await t('Flow card: Dismiss', async () => { await p.click('.flow-res >> text=Dismiss'); return !(await p.locator('.flow').count()); });
for (const h of [1, 6, 24]) await t(`Advance ${h} hour(s)`, async () => { await p.click(`[aria-label="Advance ${h} ${h === 1 ? 'hour' : 'hours'}"]`); await p.waitForTimeout(900); return (await p.locator('.chips').innerText()).includes('Demo clock'); });
await t('Guard toggle flips label', async () => { await p.click('.toggle'); const off = (await p.locator('.toggle').innerText()).includes('off'); await p.click('.toggle'); return off && (await p.locator('.toggle').innerText()).includes('on'); });
await t('Run guard now shows a message', async () => { await p.click('text=Run guard now'); await p.waitForSelector('.toast'); return true; });
await t('Toast dismiss button', async () => { await p.click('.toast >> [aria-label="Dismiss message"]'); await p.waitForTimeout(200); return true; });
await t('Reset demo clears the demo clock chip', async () => { await p.click('.demo >> text=Reset demo'); await p.waitForTimeout(1200); return !(await p.locator('.chips').innerText()).includes('Demo clock'); });
await p.click('nav >> text=Home'); await p.waitForSelector('.attn');
await t('Closed group expands and a closed row opens', async () => { await p.click('summary:has-text("Closed")'); await p.locator('.closed .rowlink').first().click(); await p.waitForSelector('.drawer'); await p.keyboard.press('Escape'); return true; });
await t('What is real? disclosure expands and shows PayPal status', async () => { await p.click('text=What is real?'); const x = await p.locator('#real').innerText(); await p.click('text=What is real?'); return /oauth/.test(x) && /Simulated/.test(x); });
await t('How it decided disclosure opens and lists the score', async () => { await p.locator('.rowlink').first().click(); await p.waitForSelector('.drawer'); await p.click('summary:has-text("How it decided")'); const x = await p.locator('.drawer').innerText(); await p.keyboard.press('Escape'); return /Evidence score/.test(x) && /Decision/.test(x); });
await t('Table row link opens drawer', async () => { await p.locator('.rowlink').first().click(); await p.waitForSelector('.drawer'); await p.keyboard.press('Escape'); return true; });
await t('Review and file opens drawer', async () => { await p.click('text=Review and file'); await p.waitForSelector('.drawer'); return true; });
await t('Drawer Close button', async () => { await p.click('.drawer >> text=Close'); await p.waitForTimeout(300); return !(await p.locator('.drawer').count()); });
await p.click('text=Review and file'); await p.waitForSelector('.drawer');
await t('File response: dialog opens, focus on Cancel, Tab stays inside', async () => { await p.click('.drawer >> text=File response'); await p.waitForSelector('.modal'); const f = await p.evaluate(() => document.activeElement.textContent); for (let i = 0; i < 5; i++) await p.keyboard.press('Tab'); const inside = await p.evaluate(() => !!document.activeElement.closest('.modal')); return f === 'Cancel' && inside; });
await t('Dialog: Escape closes the dialog only', async () => { await p.keyboard.press('Escape'); await p.waitForTimeout(250); return !(await p.locator('.modal').count()) && (await p.locator('.drawer').count()) === 1; });
await t('Dialog: Cancel button', async () => { await p.click('.drawer >> text=File response'); await p.click('.modal >> text=Cancel'); return !(await p.locator('.modal').count()); });
await t('Edit the draft, confirm File response -> Filed', async () => { await p.fill('#notes', 'Edited by the seller before filing.'); await p.click('.drawer >> text=File response'); await p.click('.modal >> text=File response'); await p.waitForSelector('.toast:has-text("filed")', { timeout: 15000 }); return (await p.locator('.drawer').innerText()).includes('Filed by'); });
await t('Filed state persists across reload', async () => { await p.reload(); await p.waitForSelector('.drawer'); return (await p.locator('.drawer').innerText()).includes('Filed by'); });
await t('Fast-forward PayPal review (simulated)', async () => { await p.click('text=/Fast-forward/'); await p.waitForTimeout(1200); return (await p.locator('.drawer').innerText()).includes('(simulated)'); });
await p.keyboard.press('Escape');
await t('Accept claim: dialog states refund and cannot be undone, confirm -> Accepted', async () => { await p.locator('.page > .tablewrap .rowlink').first().click(); await p.waitForSelector('.drawer'); if (!(await p.locator('text=Accept claim and refund buyer').count())) return 'second row not actionable'; await p.click('.drawer >> text=Accept claim and refund buyer'); const txt = await p.locator('.modal').innerText(); await p.click('.modal >> text=Accept claim and refund buyer'); await p.waitForSelector('.toast:has-text("accepted")', { timeout: 15000 }); return /cannot be undone/.test(txt); });
await p.keyboard.press('Escape');
await t('Idempotent re-file shows "already filed"', async () => { const r = await p.evaluate(async () => { const s = localStorage.getItem('dd-session'); const j = await (await fetch('/api/state', { headers: { 'X-Session': s } })).json(); const f = j.disputes.find((d) => d.state === 'FILED'); const rr = await fetch(`/api/disputes/${f.id}/file`, { method: 'POST', headers: { 'X-Session': s, 'content-type': 'application/json' }, body: '{}' }); return [rr.status, (await rr.json()).idempotent_replay]; }); return r[0] === 200 && r[1] === true ? 'API returns idempotent_replay (UI wording checked in code)' : JSON.stringify(r); });
await t('Evidence page figures present', async () => { await p.click('nav >> text=The evidence'); const x = await p.locator('.page').innerText(); return ['1,186,812', '1,349,343', '1,082,247', '401,484', '22%', '40%', 'not PayPal commerce data'].every((s) => x.includes(s)); });
await t('Failed webhook shows recovery (simulated 504)', async () => { await p.click('nav >> text=Home'); await p.route('**/api/webhooks/paypal', (r) => r.fulfill({ status: 504, body: 'gateway' })); await p.click('.demo >> text=Deliver webhook'); await p.waitForSelector('.flow.banner.bad'); await p.unroute('**/api/webhooks/paypal'); await p.click('.flow button:has-text("Refresh the board")'); await p.waitForTimeout(500); return !(await p.locator('.flow').count()); });
await t('409 on action shows "changed" message', async () => { await p.click('.demo >> text=Reset demo'); await p.waitForTimeout(1200); await p.route('**/api/disputes/*/accept', (r) => r.fulfill({ status: 409, contentType: 'application/json', body: '{"error":"state changed"}' })); await p.locator('.rowlink').first().click(); await p.waitForSelector('.drawer'); if (!(await p.locator('.drawer >> text=Accept claim and refund buyer').count())) { await p.keyboard.press('Escape'); return 'skipped, no actionable dispute'; } await p.click('.drawer >> text=Accept claim and refund buyer'); await p.click('.modal >> text=Accept claim and refund buyer'); await p.waitForSelector('.toast:has-text("changed while you were looking")'); await p.unroute('**/api/disputes/*/accept'); return true; });
await t('NEW state renders (mocked): working note, no crash', async () => { await p.keyboard.press('Escape'); await p.route('**/api/state', async (r) => { const j = await (await r.fetch()).json(); j.disputes[0].state = 'NEW'; j.disputes[0].analysis = null; j.disputes[0].filing = null; await r.fulfill({ json: j }); }); await p.reload(); await p.waitForSelector('.attn'); const x = await p.locator('.attn').innerText(); await p.screenshot({ path: 'shots/new-state.png' }); await p.unroute('**/api/state'); return x.includes('working'); });
await ctx.close();
const m = await b.newContext({ viewport: { width: 360, height: 740 } });
await m.addInitScript(() => localStorage.setItem('dd-session', 'clickmobile1'));
const q = await m.newPage();
await q.goto(APP); await q.waitForSelector('.attn');
await t('Mobile: Menu opens the sidebar and navigates', async () => { await q.click('text=Menu'); await q.waitForTimeout(300); await q.click('nav >> text=All disputes'); await q.waitForTimeout(300); return (await q.locator('h1').innerText()).includes('All disputes'); });
await t('Mobile: no horizontal scroll', async () => (await q.evaluate(() => document.documentElement.scrollWidth - innerWidth)) <= 0);
await t('Keyboard: Tab reaches controls with a visible focus ring', async () => { await q.keyboard.press('Tab'); await q.keyboard.press('Tab'); const o = await q.evaluate(() => getComputedStyle(document.activeElement).outlineStyle); return o !== 'none'; });
await t('No uncaught page errors or native dialogs', async () => errs.length === 0 ? true : errs.join('; '));
await b.close();
const fails = res.filter((r) => !r[1]).length;
writeFileSync('shots/clickthrough.json', JSON.stringify(res));
console.log(fails ? `${fails} FAILED` : 'ALL PASSED');
