// Reads the real colour tokens from src/styles.css for both themes and checks
// every text/background pair the UI uses. Writes CONTRAST.md. Exits 1 on failure.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const css = readFileSync(join(root, 'src/styles.css'), 'utf8');

function block(sel) {
  const i = css.indexOf(sel + ' {');
  if (i < 0) throw new Error('missing block ' + sel);
  const body = css.slice(css.indexOf('{', i) + 1, css.indexOf('\n}', i));
  const t = {};
  for (const m of body.matchAll(/--([a-z0-9-]+):\s*(#[0-9a-fA-F]{3,6})\s*;/g)) t[m[1]] = m[2];
  return t;
}
const dark = block(':root');
const light = { ...dark, ...block(":root[data-theme='light']") };

const lum = (hex) => {
  let h = hex.slice(1); if (h.length === 3) h = [...h].map((c) => c + c).join('');
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
    .map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };

// [label, foreground token, background token, minimum ratio]
const PAIRS = [
  ['Body text on page', 'text', 'bg'], ['Body text on panel', 'text', 'surface'], ['Body text on raised panel', 'text', 'surface-2'],
  ['Secondary text on panel', 'text-2', 'surface'], ['Secondary text on page', 'text-2', 'bg'], ['Secondary text on raised panel', 'text-2', 'surface-2'],
  ['Muted text on panel', 'muted', 'surface'], ['Muted text on page', 'muted', 'bg'], ['Muted text on raised panel', 'muted', 'surface-2'],
  ['Muted text on amber panel', 'muted', 'amber-wash'], ['Body text on amber panel', 'text', 'amber-wash'], ['Secondary text on amber panel', 'text-2', 'amber-wash'],
  ['Body text on red panel', 'text', 'red-wash'], ['Muted text on red panel', 'muted', 'red-wash'],
  ['Countdown amber text on panel', 'amber-ink', 'surface'], ['Countdown amber text on amber panel', 'amber-ink', 'amber-wash'],
  ['Countdown amber text on page', 'amber-ink', 'bg'], ['Countdown amber text on raised panel', 'amber-ink', 'surface-2'],
  ['Countdown red text on panel', 'red-ink', 'surface'], ['Countdown red text on red panel', 'red-ink', 'red-wash'], ['Countdown red text on page', 'red-ink', 'bg'],
  ['Dial digits (amber) on dial', 'dial-amber', 'dial-bg'], ['Dial digits (pale amber) on dial', 'dial-ok', 'dial-bg'], ['Dial digits (red) on dial', 'dial-red', 'dial-bg'],
  ['Dial digits (done) on dial', 'dial-good', 'dial-bg'], ['Dial labels on dial', 'dial-muted', 'dial-bg'], ['Dial days on dial', 'dial-text', 'dial-bg'],
  ['Good chip text on panel', 'good-ink', 'surface'], ['Good text on good banner', 'text', 'good-wash'], ['Good text on page', 'good-ink', 'bg'],
  ['Clay (warning) chip text on panel', 'clay-ink', 'surface'], ['Clay text on clay banner', 'clay-ink', 'clay-wash'], ['Body text on clay banner', 'text', 'clay-wash'],
  ['Clay text on page', 'clay-ink', 'bg'],
  ['Primary button text', 'on-accent', 'accent'], ['Primary button hover text', 'on-accent', 'accent-hover'],
  ['Danger button text', 'on-clay', 'clay-solid'], ['Danger outline button text', 'clay-ink', 'surface'],
  ['Link and row-link text', 'text', 'surface'], ['Link text on amber panel', 'text', 'amber-wash'],
  ['Code text', 'code-text', 'code-bg'], ['Code label', 'code-muted', 'code-bg'],
  ['Sidebar count badge', 'text-2', 'bg'], ['Active nav item', 'text', 'surface-2'],
  ['Toast text', 'text', 'surface'],
].map(([l, f, b]) => [l, f, b, 4.5]);

let fail = 0;
let md = '# Contrast report\n\nGenerated by `npm run contrast` from the colour tokens in `src/styles.css`. Every text pair must reach 4.5:1 (WCAG AA for normal text). The same threshold is applied to large and bold text, which only needs 3:1, so the margin is generous.\n\n';
for (const [name, T] of [['Dark theme', dark], ['Light theme', light]]) {
  md += `## ${name}\n\n| Pair | Foreground | Background | Ratio | Needs | Result |\n|---|---|---|---|---|---|\n`;
  console.log(`\n${name}`);
  for (const [label, f, b, need] of PAIRS) {
    if (!T[f] || !T[b]) { console.log('MISSING token', f, b); fail++; continue; }
    const r = ratio(T[f], T[b]);
    const ok = r >= need; if (!ok) fail++;
    md += `| ${label} | ${f} | ${b} | ${r.toFixed(2)}:1 | ${need}:1 | ${ok ? 'pass' : 'FAIL'} |\n`;
    console.log(`${ok ? 'pass' : 'FAIL'}  ${r.toFixed(2).padStart(5)}:1  ${label}`);
  }
  md += '\n';
}
md += fail ? `**${fail} pair(s) failed.**\n` : '**All pairs pass in both themes.**\n';
writeFileSync(join(root, 'CONTRAST.md'), md);
console.log(fail ? `\n${fail} failing` : '\nAll pairs pass');
process.exit(fail ? 1 : 0);
